### PR TITLE
correction brightness range in white mode to 1-255

### PR DESCRIPTION
**Pull request by nao-pon**
As far as I can tell, the brightness range in white mode seems to be 1-255.

### CODE REVIEW

**Comment by ollo69** [comment]
This is not a rule!. I have a light that have range 10-1000. If we change in this way we broke for all the other. Need further investigation.

**Comment by nao-pon** [comment]
@ollo69 Yes, I understand. The brightness range is not included in the API response, so I think we need to be able to specify it as an option.

**Comment by ollo69** [comment]
Yes, but should be something simple, like type 0 and type 1, hoping in limited case. I think that ask to the user to specify the brightness range used by their bulb will just create errors and confusion...

**Comment by ollo69** [comment]
I close this PR because outdated

**Pull request closed without merging**
